### ISSUE TITLE
Eclipse Mars M6 Fail to start with Plugin

### ISSUE THREAD

**Issue by zaxeer** [jeeeyul/eclipse-themes#233] opened 2015-05-08 15:19 UTC
Hello jeeeyul,

I am using you pluging form very long time, and recently i try to switch to eclipse-jee-mars-M6-win32-x86_64 and after setting your plugin and restarting eclipse have errors. I think in workspace/meta/logs some exceptions will be helpful.

Thanks for fixing.
Regards
Zaheer

**Comment by matthias-fue** [comment] 2015-05-13 13:46
This is probably a duplicate of #229

**Closed** 2015-06-09 09:42 UTC
