### ISSUE TITLE
NoSuchMethodError on Eclipse Mars 4.5M6 on startup

### ISSUE THREAD

**Issue by Jona5** [jeeeyul/eclipse-themes#232] opened 2015-04-30 09:23 UTC
<pre>
java.lang.NoSuchMethodError: org.eclipse.e4.ui.css.swt.helpers.CSSSWTColorHelper.getRGB(Lorg/w3c/dom/css/CSSValue;)Lorg/eclipse/swt/graphics/RGB;
	at net.jeeeyul.eclipse.themes.css.internal.handlers.JTabCSSPropertyHandler.applyCSSProperty(JTabCSSPropertyHandler.java:679)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyCSSProperty(AbstractCSSEngine.java:734)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyleDeclaration(AbstractCSSEngine.java:520)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:413)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:354)
	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.applyStyles(ThemeEngine.java:516)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$6.setClassnameAndId(PartRenderingEngine.java:1282)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.setCSSInfo(SWTPartRenderer.java:113)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.bindWidget(SWTPartRenderer.java:130)
</pre>

**Comment by lowne** [comment] 2015-05-06 13:12
Same here - wish I didn't update 😭

**Comment by matthias-fue** [comment] 2015-05-13 13:43
This is a duplicate of #229

**Closed** 2015-06-03 10:17 UTC
